import React from "react";
import jsPDF from "jspdf";
import { FaFilePdf } from "react-icons/fa";

const GeneratePdf = ({ contest }) => {
    const formatDuration = (minutes) => {
        const days = Math.floor(minutes / (24 * 60));
        const hours = Math.floor((minutes % (24 * 60)) / 60);
        const mins = minutes % 60;

        let durationString = '';

        if (days > 0) {
            durationString += `${days}d `;
        }

        if (hours > 0 || days > 0) {
            durationString += `${hours}h `;
        }

        if (mins > 0 || (hours === 0 && days === 0)) {
            durationString += `${mins}m`;
        }

        return durationString.trim();
    };

    const handleGeneratePdfClick = () => {
        const doc = new jsPDF();
        doc.setFontSize(16);
        doc.text("Contest Details", 10, 10);

        doc.setFontSize(12);
        doc.text(`Contest Name: ${contest.name}`, 10, 30);
        doc.text(`Start Date: ${new Date(contest.startDate).toLocaleString([], { month: '2-digit', day: '2-digit', year: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true })}`, 10, 40);
        doc.text(`End Date: ${new Date(contest.endDate).toLocaleString([], { month: '2-digit', day: '2-digit', year: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true })}`, 10, 50);
        doc.text(`Duration: ${formatDuration(contest.duration)}`, 10, 60);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text("Generated by Contest Management System", 10, 80);

        doc.save(`${contest.name}.pdf`);
    };

    return (
        <button
            className="bg-blue-500 hover:bg-blue-600 text-white font-semibold px-4 py-2 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 flex items-center"
            onClick={() => handleGeneratePdfClick(contest)}
        >
            <FaFilePdf className="mr-2" /> Generate PDF
        </button>
    );
};

export default GeneratePdf;
